#!/bin/bash

# Compares compat32 to base versions
# of packages and highlights differences

# Written by JK Wood <joshuakwood@gmail.com>

# Script is released under the Dog-on-Fire License:
# If use of this script causes your dog to catch on fire,
# you agree to send me five dollars.  Or a picture
# of the dog on fire.
# Otherwise, you're on your own.  I've tested the script
# on my own computer, and it hasn't broken anything.
# So if it does it on your computer, that falls in
# the realm of "Not my problem."
#
# Of course, if you'll send a bug report to the above
# email address, I may be able to see what you did
# wrong and prevent it from happening in the future.
# In which case, I may just send YOU five dollars.

# Oh, and feel free to copy it and modify it as you
# see fit. Or as I see fit. Or as I fit. Although
# that is unlikely, as I am rather tall.

cd /var/log/packages/
got_one=1

for i in *compat32; do
  base_name=$(echo $i | rev | cut -d- -f 5- | rev)
  compat32_ver=$(echo $i | rev | cut -d- -f 3 | rev)
  base_pkg_name=$(echo $(ls -1 $(echo $i | rev | cut -d- -f 5- | rev)-[0-9]*))
  base_ver=$(echo $base_pkg_name | rev | cut -d- -f 3 | rev)

  if [ $compat32_ver != $base_ver ]
  then
    if [ $got_one == 1 ]
    then
      echo "Package, 32 Ver, Base Ver"
      got_one=0
    fi
    echo $base_name $compat32_ver $base_ver
  fi
done

if [ $got_one == 1 ]
then
  echo "All compat32 versions match"
fi
