#!/bin/bash
# Script to view the contents of a package
# Written by JK Wood <joshuakwood@gmail.com>

if [ $# != 1 ]; then
  echo
  echo "Script for viewing package contents"
  echo "Only displays first matching package"
  echo
  echo "Usage: $0 PACKAGE_NAME"
  echo
  exit 1
fi

# First, try to find a package starting with that name
if [ $(ls -1 /var/log/packages/$1*| grep -i -m 1 $1) ]; then
  less $(ls -1 /var/log/packages/$1* | grep -i -m 1 $1)
# If you didn't find a package starting with that name, search the whole thing
elif [ $(ls -1 /var/log/packages/ | grep -i -m 1 $1) ]; then
  less $(find /var/log/packages/ -iname $(ls /var/log/packages/ | grep -i -m 1 $1))
# Must not have one
else
  echo "No package matching that name found." 
fi

exit;
