#!/bin/bash
# Script to view the contents of a package
# Written by JK Wood <joshuakwood@gmail.com>

# Script is released under the Dog-on-Fire License:
# If use of this script causes your dog to catch on fire,
# you agree to send me five dollars.  Or a picture
# of the dog on fire.
# Otherwise, you're on your own.  I've tested the script
# on my own computer, and it hasn't broken anything.
# So if it does it on your computer, that falls in
# the realm of "Not my problem."
#
# Of course, if you'll send a bug report to the above
# email address, I may be able to see what you did
# wrong and prevent it from happening in the future.
# In which case, I may just send YOU five dollars.

# Oh, and feel free to copy it and modify it as you
# see fit. Or as I see fit. Or as I fit. Although
# that is unlikely, as I am rather tall.

if [ $# != 1 ]; then
  echo
  echo "Script for viewing package contents"
  echo "Only displays first matching package"
  echo
  echo "Usage: $0 PACKAGE_NAME"
  echo
  exit 1
fi

# First, try to find a package starting with that name
if [ $(ls -1 /var/log/packages/$1*| grep -i -m 1 $1) ]; then
  less $(ls -1 /var/log/packages/$1* | grep -i -m 1 $1)
# If you didn't find a package starting with that name, search the whole thing
elif [ $(ls -1 /var/log/packages/ | grep -i -m 1 $1) ]; then
  less $(find /var/log/packages/ -iname $(ls /var/log/packages/ | grep -i -m 1 $1))
# Must not have one
else
  echo "No package matching that name found." 
fi

exit;
