#!/bin/bash
# Script to find library references to the second parm
# in the directory specified in the first
# parameter.

# Written by JK Wood <joshuakwood@gmail.com>

# Script is released under the Dog-on-Fire License:
# If use of this script causes your dog to catch on fire,
# you agree to send me five dollars.  Or a picture
# of the dog on fire.
# Otherwise, you're on your own.  I've tested the script
# on my own computer, and it hasn't broken anything.
# So if it does it on your computer, that falls in
# the realm of "Not my problem."
#
# Of course, if you'll send a bug report to the above
# email address, I may be able to see what you did
# wrong and prevent it from happening in the future.
# In which case, I may just send YOU five dollars.

# Oh, and feel free to copy it and modify it as you
# see fit. Or as I see fit. Or as I fit. Although
# that is unlikely, as I am rather tall.

cd "$1"
searchterm="$2"

for i in *; do
  results=$(ldd $i 2>&1 | grep -i $searchterm)
  num_results=$(ldd $i 2>&1 | grep -i $searchterm | wc -c)

  if [ $num_results -gt 0 ]
  then
    echo $i
    echo $results
  fi
done
